
name: 'dbt_snowflake_demo'
version: '1.0.0'

profile: 'dbt_snowflake_demo'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_snowflake_demo:

    staging:
      +schema: STAGING
      +materialized: view

    intermediate:
      +schema: INTERMEDIATE
      +materialized: view

    marts:
      +schema: MARTS
      +materialized: table
